import { useState, useEffect } from 'react';
import { claimFaucet } from '../api';
import { useWallet } from '../hooks/useWallet';

const LABEL_MAP = {
  AMM_TKA_TKB:  'AMM Pool (TKA/TKB)',
  AMM_TKA_USDC: 'AMM Pool (TKA/USDC)',
  AMMFactory:   'AMMFactory',
  TokenAlpha:   'Token Alpha (TKA)',
  TokenBeta:    'Token Beta (TKB)',
  USDC:         'USDC (test)',
};

const FALLBACK = {
  network: 'Sepolia Testnet',
  chainId: '11155111',
  contracts: {},
};

const STEPS = [
  { n: 1, title: 'Configure .env', desc: 'Add PRIVATE_KEY and INFURA_URL (or SEPOLIA_RPC_URL) to your .env file.' },
  { n: 2, title: 'Fund your wallet', desc: 'Get Sepolia ETH from sepoliafaucet.com or Alchemy\'s Sepolia faucet.' },
  { n: 3, title: 'Deploy contracts', desc: 'Run: npm run deploy:sepolia — deploys AMM + factory + tokens + seeds liquidity.' },
  { n: 4, title: 'Update addresses', desc: 'Copy the printed addresses into src/config/contracts.js (auto-generated by deploy script).' },
  { n: 5, title: 'Interact on-chain', desc: 'Connect MetaMask to Sepolia, use the Swap/Pool tabs — transactions go on-chain.' },
];

export function TestnetPanel({ showMessage }) {
  const { address, isConnected, connect } = useWallet();
  const [faucetLoading, setFaucetLoading] = useState(false);
  const [faucetResult,  setFaucetResult]  = useState(null);
  const [copied, setCopied] = useState('');
  const [deployed, setDeployed] = useState(FALLBACK);

  useEffect(() => {
    fetch('/contracts.json')
      .then(r => r.ok ? r.json() : null)
      .then(data => {
        if (!data?.contracts) return;
        const contracts = {};
        Object.entries(data.contracts).forEach(([key, addr]) => {
          contracts[LABEL_MAP[key] || key] = { address: addr, verified: false };
        });
        setDeployed({
          network: 'Sepolia Testnet',
          chainId: data.chainId || '11155111',
          contracts,
          deployedAt: data.deployedAt,
        });
      })
      .catch(() => {});
  }, []);

  const copyAddress = (addr) => {
    navigator.clipboard.writeText(addr).catch(() => {});
    setCopied(addr);
    setTimeout(() => setCopied(''), 2000);
  };

  const handleFaucet = async () => {
    if (!isConnected) { showMessage('Connect your wallet first', 'error'); return; }
    setFaucetLoading(true);
    try {
      const { data } = await claimFaucet(address);
      if (data.success) {
        setFaucetResult(data.data);
        showMessage(`Faucet claimed! 1,000 TKA + 1,000 TKB + 3M USDC (demo)`);
      }
    } catch (err) {
      showMessage(err.response?.data?.error || 'Faucet error', 'error');
    } finally { setFaucetLoading(false); }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="glass rounded-2xl shadow-card p-6 gradient-border">
        <div className="flex items-start justify-between">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="w-2 h-2 rounded-full bg-yellow-400 live-dot" />
              <span className="text-xs font-medium text-yellow-400">{deployed.network}</span>
              <span className="text-xs text-textDim">Chain ID: {deployed.chainId}</span>
            </div>
            <h2 className="font-display font-bold text-xl text-text">Testnet Deployment</h2>
            <p className="text-sm text-textMuted mt-1">
              {deployed.deployedAt
                ? `Deployed ${new Date(deployed.deployedAt).toLocaleDateString()} — live on Sepolia`
                : 'Deploy the AMM to Sepolia and interact with real on-chain transactions.'}
            </p>
          </div>
          <div className="hidden md:flex flex-col items-end gap-2">
            {isConnected ? (
              <span className="px-3 py-1.5 rounded-lg bg-success/15 text-success text-xs font-mono font-medium">
                {address?.slice(0, 6)}…{address?.slice(-4)} Connected
              </span>
            ) : (
              <button onClick={connect} className="px-4 py-2 rounded-xl text-sm font-semibold bg-primary text-bg hover:bg-primaryHover transition-colors">
                Connect Wallet
              </button>
            )}
          </div>
        </div>
      </div>

      <div className="grid lg:grid-cols-2 gap-6">
        {/* Deployed contracts */}
        <div className="glass rounded-2xl shadow-card p-5">
          <h3 className="text-sm font-semibold text-text mb-4">Contract Addresses</h3>
          <div className="space-y-3">
            {Object.keys(deployed.contracts).length === 0 ? (
              <p className="text-xs text-textMuted italic">Loading contract addresses…</p>
            ) : Object.entries(deployed.contracts).map(([name, { address: addr, verified }]) => (
              <div key={name} className="bg-surfaceElevated rounded-xl p-3">
                <div className="flex items-center justify-between mb-1.5">
                  <span className="text-xs font-medium text-text">{name}</span>
                  {verified && (
                    <span className="text-[10px] px-1.5 py-0.5 rounded bg-success/15 text-success">Verified</span>
                  )}
                </div>
                <div className="flex items-center gap-2">
                  <code className="text-[10px] text-textMuted font-mono flex-1 truncate">{addr}</code>
                  {addr.startsWith('0x') && (
                    <>
                      <button
                        onClick={() => copyAddress(addr)}
                        className="text-[10px] px-2 py-0.5 rounded bg-surfaceHover text-textMuted hover:text-primary transition-colors shrink-0"
                      >
                        {copied === addr ? 'Copied!' : 'Copy'}
                      </button>
                      <a
                        href={`https://sepolia.etherscan.io/address/${addr}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-[10px] px-2 py-0.5 rounded bg-surfaceHover text-textMuted hover:text-accent transition-colors shrink-0"
                      >
                        Etherscan
                      </a>
                    </>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Faucet */}
        <div className="glass rounded-2xl shadow-card p-5">
          <h3 className="text-sm font-semibold text-text mb-2">Demo Token Faucet</h3>
          <p className="text-xs text-textMuted mb-4">Claim test tokens to try the AMM. Cooldown: 24 hours per address.</p>

          {!isConnected ? (
            <button onClick={connect} className="w-full py-3 rounded-xl font-semibold bg-primary text-bg hover:bg-primaryHover transition-colors text-sm">
              Connect Wallet to Claim
            </button>
          ) : (
            <button
              onClick={handleFaucet}
              disabled={faucetLoading}
              className="w-full py-3 rounded-xl font-semibold text-sm bg-accent/20 text-accent border border-accent/30 hover:bg-accent/30 transition-colors disabled:opacity-50"
            >
              {faucetLoading ? 'Claiming…' : '💧 Claim Demo Tokens'}
            </button>
          )}

          {faucetResult && (
            <div className="mt-4 rounded-xl bg-success/10 border border-success/20 p-3 space-y-1.5 animate-slide-up">
              <p className="text-xs font-semibold text-success mb-2">Tokens received</p>
              {Object.entries(faucetResult.tokens || {}).map(([sym, amt]) => (
                <div key={sym} className="flex justify-between text-xs">
                  <span className="text-textMuted">{sym}</span>
                  <span className="font-mono text-text">{parseFloat(amt).toLocaleString()}</span>
                </div>
              ))}
              <p className="text-[10px] text-textDim mt-2">{faucetResult.message}</p>
            </div>
          )}

          <div className="mt-4 pt-4 border-t border-border space-y-2">
            <p className="text-xs text-textMuted font-medium">External faucets for Sepolia ETH:</p>
            <ul className="space-y-1 text-xs text-textDim">
              <li>• sepoliafaucet.com (Alchemy)</li>
              <li>• faucet.sepolia.dev</li>
              <li>• cloud.google.com/application/web3/faucet/ethereum/sepolia</li>
            </ul>
          </div>
        </div>

        {/* Deployment guide */}
        <div className="glass rounded-2xl shadow-card p-5 lg:col-span-2">
          <h3 className="text-sm font-semibold text-text mb-4">Deployment Guide</h3>
          <div className="grid md:grid-cols-5 gap-3">
            {STEPS.map(({ n, title, desc }) => (
              <div key={n} className="relative">
                {n < STEPS.length && (
                  <div className="hidden md:block absolute top-4 left-full w-full h-px bg-border z-0" style={{ transform: 'translateX(-50%)' }} />
                )}
                <div className="relative z-10 flex flex-col items-center text-center gap-2">
                  <div className="w-8 h-8 rounded-full bg-gradient-primary flex items-center justify-center text-white font-bold text-sm">
                    {n}
                  </div>
                  <p className="text-xs font-semibold text-text">{title}</p>
                  <p className="text-[10px] text-textMuted leading-relaxed">{desc}</p>
                </div>
              </div>
            ))}
          </div>

          <div className="mt-5 p-4 rounded-xl bg-surfaceElevated border border-border">
            <p className="text-xs text-textMuted font-medium mb-2">Quick deploy commands</p>
            <div className="space-y-1.5">
              {[
                'cp .env.example .env  # Fill in PRIVATE_KEY + INFURA_URL',
                'npm run compile       # Compile contracts',
                'npm run deploy:sepolia # Deploy to Sepolia testnet',
              ].map(cmd => (
                <div key={cmd} className="flex items-center gap-2">
                  <span className="text-primary text-xs">$</span>
                  <code className="text-xs font-mono text-text">{cmd}</code>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
